/*------------------------------------------------------------------------------------------------
 *  RDMT STUDIOS 1986. All rights reserved.
 *  Licensed under the Apache 2.0 License. See LICENSE in the project root for license information.
 *-----------------------------------------------------------------------------------------------*/


export interface UCECursorController {
    /**
     * ### Show cursor on a screen 
     * @returns void
     */
    Display(): void,
    /**
     * ### Hide cursor
     * @returns void
     */
    Hide(): void,
    /**
     * ### Start cursor inner rendering loop
     * Render loop is responsible for cursor inner logic processing,
     * which changes its state and UI.
     * @returns void
     */
    Render(): void,
    /**
     * ### Stop cursor inner render loop
     * Render loop is responsible for cursor inner logic processing,
     * which changes its state and UI.
     * @returns void
     */
    Freeze(): void,
};


/**
 * Generated by UCEEngine event-objects, which passed is as an argument
 * to event-handlers, when event of type {@link UCEEventType} is fired.
 * */
export interface UCEEvent {
    target: Element|null;
    tag: string|null;
    x: number;
    y: number;
}

/**
 * Callback, which handles cursor {@link UCEEventType} events.
 * Handled event is {@link UCEEvent}
 */
export type UCEEventHandler = (e: UCEEvent) => void

