/*------------------------------------------------------------------------------------------------
 *  RDMT STUDIOS 1986. All rights reserved.
 *  Licensed under the Apache 2.0 License. See LICENSE in the project root for license information.
 *-----------------------------------------------------------------------------------------------*/


export interface UCECursorController {
    /**
     * ### Show cursor on a screen 
     * @returns void
     */
    Display(): void,
    /**
     * ### Remove cursor from the screen
     * @returns void
     */
    Remove(): void,
    /**
     * ### Start cursor inner rendering loop
     * Render loop is responsible for cursor inner logic processing,
     * which changes its state and UI.
     * @returns void
     */
    Render(): void,
    /**
     * ### Stop cursor inner render loop
     * Render loop is responsible for cursor inner logic processing,
     * which changes its state and UI.
     * @returns void
     */
    Freeze(): void,
    /**
     * ### Set shift between real user pointer and UserCursor UI positions
     * How it works - for example user is holding his mouse pointer on a x: 10 and y: 20
     * coordinates. So, by default, cursor position wound be changed to x: 10 and y: 20,
     * but cursor width and height are, for example, 5px and 5px respectively. On a screen
     * it wound look like cursor triggers events when it's only his left upper corner hits a html node.
     * 
     * So to 'fix' that, you can set xDifferencePX and yDifferencePX. In this situatuation, after
     * you set this values to 5 and 5, cursor will look proper and trigger events when its center
     * hits a node.
     * @param xDifferencePX difference between user real pointer on a screen and a cursor ui position for X coordinate
     * @param yDifferencePX difference between user real pointer on a screen and a cursor ui position for Y coordinate
     * @deprecated
     * @returns void
     */
    // SetShift(xDifferencePX?: number, yDifferencePX?: number): void,
    /**
     * ### Reference a user pointer node withing a callback
     * @deprecated
     * @returns a cursor node
     */
    // AccessCursorUI(accessCallback: (cursorNode: HTMLDivElement) => void): void,
};


/**
 * Generated by UCEEngine event-objects, which passed is as an argument
 * to event-handlers, when event of type {@link UCEEventType} is fired.
 * */
export interface UCEEvent {
    target: Element|null;
    tag: string|null;
    x: number;
    y: number;
}

/**
 * Callback, which handles cursor {@link UCEEventType} events.
 * Handled event is {@link UCEEvent}
 */
export type UCEEventHandler = (e: UCEEvent) => void

