
/** Type id's of cursor possible events. */
export type UCEEventType =
    'click'             |
    'contextmenu'       |
    'mousedown'         |
    'mouseup'           |
    'tagChange'         |
    'targetChange'      |
    'cursorDisplayd'    |
    'cursorWillRemove'

/**
 * Generated by UCEEngine event-objects, which passed is as an argument
 * to event-handlers, when event of type {@link UCEEventType} is fired.
 * */
export interface UCEEvent {
    target: Element|null;
    tag: string|null;
    x: number;
    y: number;
}

/**
 * Callback, which handles cursor {@link UCEEventType} events.
 * Handled event is {@link UCEEvent}
 */
export type UCEEventHandler = (e: UCEEvent) => void

/**
 * Internal registry of events of cursor object.
 * Not managed manually.
 */
export type UCECursorEventsRegistry = Map<UCEEventType, Map<UCEEventHandler, true>>
